### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by mrn-aglic** [jrsearles/SandBoxr#10]
The library seems abandoned. Are there any plans to continue its development in the future?

**Comment by jrsearles** [comment]
No, it's not abandoned. It implements the complete ECMAScript 5.1 specification. I started implementing 6 (ES2015) and implemented quite a bit of it, but realized that some major refactoring would be needed to support generator functions. I haven't felt compelled to go much further because it does everything i need already and haven't received requests for support or additional features.

Is there a particular feature you are looking for or issue you are having?

**Comment by mrn-aglic** [comment]
Hi, sorry for suggesting that the library is abandon. I was looking at different libraries (similiar to js-interpreter) for a potential proof-of-concept project really, and wanted to see what was the state of this one. 
Well, the only feature that seems missing (that I can think of) for me is stepping/pausing, which is outlined in the Readme. 

Anyway, I'm still in the phase of just checking out what's out there.
